// 个人中心-团队列表-会员状态文案字典。
// 按站点支持的语言维护，作为 Strapi CMS 未提供对应语言或字段时的兜底翻译。
// 字典键：free（非会员）、vip（会员通用）、month（月卡）、year（年卡）、life（永久）。
export const memberStatusCopy = {
  'zh-CN': {
    free: '普通用户',
    vip: 'VIP用户',
    month: '月卡会员',
    year: '年卡会员',
    life: '永久会员',
  },
  en: {
    free: 'Regular User',
    vip: 'VIP User',
    month: 'Monthly Member',
    year: 'Annual Member',
    life: 'Lifetime Member',
  },
  'zh-TW': {
    free: '普通用戶',
    vip: 'VIP用戶',
    month: '月卡會員',
    year: '年卡會員',
    life: '永久會員',
  },
  id: {
    free: 'Pengguna Biasa',
    vip: 'Pengguna VIP',
    month: 'Anggota Bulanan',
    year: 'Anggota Tahunan',
    life: 'Anggota Seumur Hidup',
  },
  ms: {
    free: 'Pengguna Biasa',
    vip: 'Pengguna VIP',
    month: 'Ahli Bulanan',
    year: 'Ahli Tahunan',
    life: 'Ahli Sepanjang Hayat',
  },
  th: {
    free: 'ผู้ใช้ทั่วไป',
    vip: 'ผู้ใช้ VIP',
    month: 'สมาชิกรายเดือน',
    year: 'สมาชิกรายปี',
    life: 'สมาชิกตลอดชีพ',
  },
  vi: {
    free: 'Người dùng thường',
    vip: 'Người dùng VIP',
    month: 'Thành viên tháng',
    year: 'Thành viên năm',
    life: 'Thành viên trọn đời',
  },
  fil: {
    free: 'Karaniwang User',
    vip: 'VIP User',
    month: 'Miyembrong Buwanan',
    year: 'Miyembrong Taunan',
    life: 'Miyembrong Panghabambuhay',
  },
  es: {
    free: 'Usuario Normal',
    vip: 'Usuario VIP',
    month: 'Miembro Mensual',
    year: 'Miembro Anual',
    life: 'Miembro Vitalicio',
  },
  pt: {
    free: 'Utilizador Normal',
    vip: 'Utilizador VIP',
    month: 'Membro Mensal',
    year: 'Membro Anual',
    life: 'Membro Vitalício',
  },
  ar: {
    free: 'مستخدم عادي',
    vip: 'مستخدم VIP',
    month: 'عضو شهري',
    year: 'عضو سنوي',
    life: 'عضو مدى الحياة',
  },
  ja: {
    free: '一般ユーザー',
    vip: 'VIPユーザー',
    month: '月額会員',
    year: '年額会員',
    life: '永久会員',
  },
  tr: {
    free: 'Normal Kullanıcı',
    vip: 'VIP Kullanıcı',
    month: 'Aylık Üye',
    year: 'Yıllık Üye',
    life: 'Ömür Boyu Üye',
  },
  it: {
    free: 'Utente Normale',
    vip: 'Utente VIP',
    month: 'Membro Mensile',
    year: 'Membro Annuale',
    life: 'Membro a Vita',
  },
  de: {
    free: 'Normaler Benutzer',
    vip: 'VIP-Benutzer',
    month: 'Monatsmitglied',
    year: 'Jahresmitglied',
    life: 'Lebenslanges Mitglied',
  },
  fr: {
    free: 'Utilisateur Normal',
    vip: 'Utilisateur VIP',
    month: 'Membre Mensuel',
    year: 'Membre Annuel',
    life: 'Membre à Vie',
  },
  ko: {
    free: '일반 사용자',
    vip: 'VIP 사용자',
    month: '월간 회원',
    year: '연간 회원',
    life: '평생 회원',
  },
  ru: {
    free: 'Обычный пользователь',
    vip: 'VIP-пользователь',
    month: 'Месячный участник',
    year: 'Годовой участник',
    life: 'Пожизненный участник',
  },
  pl: {
    free: 'Zwykły Użytkownik',
    vip: 'Użytkownik VIP',
    month: 'Członek Miesięczny',
    year: 'Członek Roczny',
    life: 'Członek Dożywotni',
  },
  nl: {
    free: 'Normale Gebruiker',
    vip: 'VIP-gebruiker',
    month: 'Maandlid',
    year: 'Jaarlid',
    life: 'Levenslang Lid',
  },
  hi: {
    free: 'सामान्य उपयोगकर्ता',
    vip: 'VIP उपयोगकर्ता',
    month: 'मासिक सदस्य',
    year: 'वार्षिक सदस्य',
    life: 'आजीवन सदस्य',
  },
  ur: {
    free: 'عام صارف',
    vip: 'VIP صارف',
    month: 'ماہانہ رکن',
    year: 'سالانہ رکن',
    life: 'تاحیات رکن',
  },
  bn: {
    free: 'সাধারণ ব্যবহারকারী',
    vip: 'VIP ব্যবহারকারী',
    month: 'মাসিক সদস্য',
    year: 'বার্ষিক সদস্য',
    life: 'আজীবন সদস্য',
  },
  fa: {
    free: 'کاربر عادی',
    vip: 'کاربر VIP',
    month: 'عضو ماهانه',
    year: 'عضو سالانه',
    life: 'عضو مادام‌العمر',
  },
}
